# Generated by Django 3.0.1 on 2019-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_date', models.DateTimeField(verbose_name='date')),
                ('type_text', models.CharField(max_length=200)),
                ('with_text', models.CharField(max_length=200)),
                ('entry_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('done_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_date', models.DateTimeField(verbose_name='date')),
                ('duedate_date', models.DateTimeField(verbose_name='date')),
                ('paper_name_text', models.CharField(max_length=200)),
                ('type_text', models.CharField(max_length=200)),
                ('where_text', models.CharField(max_length=200)),
                ('investment_value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
