# Generated by Django 3.0.1 on 2019-12-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_date',
            new_name='entry_date_date',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='type_text',
            new_name='entry_origin_dest_text',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='done_bool',
            new_name='entry_realized_bool',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='with_text',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_area_text',
            field=models.CharField(choices=[('alimentacao', 'The alimentacao choice, it is'), ('bancos', 'The bancos choice, it is'), ('calcados', 'The calcados choice, it is'), ('cama_mesa_banho', 'The cama_mesa_banho choice, it is'), ('diversao', 'The diversao choice, it is'), ('eletronico', 'The eletronico choice, it is'), ('estudo', 'The estudo choice, it is'), ('higiene', 'The higiene choice, it is'), ('investimento', 'The investimento choice, it is'), ('moradia', 'The moradia choice, it is'), ('moveis', 'The moveis choice, it is'), ('roupas', 'The roupas choice, it is'), ('saude', 'The saude choice, it is'), ('telefonia', 'The telefonia choice, it is'), ('transporte', 'The transporte choice, it is'), ('n_a', 'The n_a choice, it is')], default='n_a', max_length=30),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_payment_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_type_text',
            field=models.CharField(choices=[('in', 'The in choice, it is'), ('out', 'The out choice, it is')], default='out', max_length=30),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_with_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
