# Generated by Django 3.0.1 on 2019-12-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191227_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investment_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investment',
            name='paper_name_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='investment',
            name='type_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='investment',
            name='where_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
