# Generated by Django 3.0.1 on 2019-12-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191227_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date_date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='date_date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='duedate_date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
