# Generated by Django 3.0.1 on 2019-12-27 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20191227_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry_area_text',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_origin_dest_text',
            new_name='origin/dest',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_payment_type',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_realized_bool',
            new_name='realized',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_type_text',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_with_text',
            new_name='with',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='investment_value',
            new_name='number of paper',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='paper_name_text',
            new_name='paper name',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='type_text',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='where_text',
            new_name='where',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='date_date',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='duedate_date',
        ),
        migrations.AddField(
            model_name='investment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 27, 15, 15, 18, 873195, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='due date',
            field=models.DateField(default=datetime.datetime(2019, 12, 27, 15, 15, 28, 664405, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='price of paper',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='investment',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
