# Generated by Django 3.0.1 on 2019-12-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20191227_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='origin/dest',
            new_name='origin/Dest',
        ),
    ]
