# Generated by Django 3.0.1 on 2019-12-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20191227_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='with',
            new_name='entry_with',
        ),
    ]
